-- AlterTable
ALTER TABLE `users` ADD COLUMN `avatarFocusX` DOUBLE NOT NULL DEFAULT 50,
    ADD COLUMN `avatarFocusY` DOUBLE NOT NULL DEFAULT 50,
    ADD COLUMN `avatarZoom` DOUBLE NOT NULL DEFAULT 1;
